/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardFeedbackRouteImport } from './routes/dashboard/feedback'
import { Route as publicResetPasswordRouteImport } from './routes/(public)/reset-password'
import { Route as publicRejestracjaRouteImport } from './routes/(public)/rejestracja'
import { Route as publicRegulaminRouteImport } from './routes/(public)/regulamin'
import { Route as publicLogowanieRouteImport } from './routes/(public)/logowanie'
import { Route as publicKontaktRouteImport } from './routes/(public)/kontakt'
import { Route as publicFunkcjeRouteImport } from './routes/(public)/funkcje'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as publicCennikRouteImport } from './routes/(public)/cennik'
import { Route as DashboardIssuesIndexRouteImport } from './routes/dashboard/issues.index'
import { Route as DashboardEquipmentIndexRouteImport } from './routes/dashboard/equipment.index'
import { Route as DashboardIssuesArchiveRouteImport } from './routes/dashboard/issues.archive'
import { Route as DashboardIssuesIdRouteImport } from './routes/dashboard/issues.$id'
import { Route as DashboardEquipmentAddRouteImport } from './routes/dashboard/equipment.add'
import { Route as DashboardEquipmentIdRouteImport } from './routes/dashboard/equipment.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeedbackRoute = DashboardFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DashboardRoute,
} as any)
const publicResetPasswordRoute = publicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicRejestracjaRoute = publicRejestracjaRouteImport.update({
  id: '/rejestracja',
  path: '/rejestracja',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicRegulaminRoute = publicRegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLogowanieRoute = publicLogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicKontaktRoute = publicKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicFunkcjeRoute = publicFunkcjeRouteImport.update({
  id: '/funkcje',
  path: '/funkcje',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCennikRoute = publicCennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => publicRouteRoute,
} as any)
const DashboardIssuesIndexRoute = DashboardIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentIndexRoute = DashboardEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssuesArchiveRoute = DashboardIssuesArchiveRouteImport.update({
  id: '/issues/archive',
  path: '/issues/archive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssuesIdRoute = DashboardIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentAddRoute = DashboardEquipmentAddRouteImport.update({
  id: '/equipment/add',
  path: '/equipment/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentIdRoute = DashboardEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/cennik': typeof publicCennikRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/funkcje': typeof publicFunkcjeRoute
  '/kontakt': typeof publicKontaktRoute
  '/logowanie': typeof publicLogowanieRoute
  '/regulamin': typeof publicRegulaminRoute
  '/rejestracja': typeof publicRejestracjaRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/equipment/add': typeof DashboardEquipmentAddRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/dashboard/equipment/': typeof DashboardEquipmentIndexRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/cennik': typeof publicCennikRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/funkcje': typeof publicFunkcjeRoute
  '/kontakt': typeof publicKontaktRoute
  '/logowanie': typeof publicLogowanieRoute
  '/regulamin': typeof publicRegulaminRoute
  '/rejestracja': typeof publicRejestracjaRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/equipment/add': typeof DashboardEquipmentAddRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/dashboard/equipment': typeof DashboardEquipmentIndexRoute
  '/dashboard/issues': typeof DashboardIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/(public)/cennik': typeof publicCennikRoute
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/funkcje': typeof publicFunkcjeRoute
  '/(public)/kontakt': typeof publicKontaktRoute
  '/(public)/logowanie': typeof publicLogowanieRoute
  '/(public)/regulamin': typeof publicRegulaminRoute
  '/(public)/rejestracja': typeof publicRejestracjaRoute
  '/(public)/reset-password': typeof publicResetPasswordRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/(public)/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/equipment/add': typeof DashboardEquipmentAddRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/dashboard/equipment/': typeof DashboardEquipmentIndexRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/cennik'
    | '/forgot-password'
    | '/funkcje'
    | '/kontakt'
    | '/logowanie'
    | '/regulamin'
    | '/rejestracja'
    | '/reset-password'
    | '/dashboard/feedback'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/'
    | '/dashboard/'
    | '/dashboard/equipment/$id'
    | '/dashboard/equipment/add'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/dashboard/equipment/'
    | '/dashboard/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cennik'
    | '/forgot-password'
    | '/funkcje'
    | '/kontakt'
    | '/logowanie'
    | '/regulamin'
    | '/rejestracja'
    | '/reset-password'
    | '/dashboard/feedback'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/'
    | '/dashboard'
    | '/dashboard/equipment/$id'
    | '/dashboard/equipment/add'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/dashboard/equipment'
    | '/dashboard/issues'
  id:
    | '__root__'
    | '/(public)'
    | '/dashboard'
    | '/(public)/cennik'
    | '/(public)/forgot-password'
    | '/(public)/funkcje'
    | '/(public)/kontakt'
    | '/(public)/logowanie'
    | '/(public)/regulamin'
    | '/(public)/rejestracja'
    | '/(public)/reset-password'
    | '/dashboard/feedback'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/(public)/'
    | '/dashboard/'
    | '/dashboard/equipment/$id'
    | '/dashboard/equipment/add'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/dashboard/equipment/'
    | '/dashboard/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feedback': {
      id: '/dashboard/feedback'
      path: '/feedback'
      fullPath: '/dashboard/feedback'
      preLoaderRoute: typeof DashboardFeedbackRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(public)/reset-password': {
      id: '/(public)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof publicResetPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/rejestracja': {
      id: '/(public)/rejestracja'
      path: '/rejestracja'
      fullPath: '/rejestracja'
      preLoaderRoute: typeof publicRejestracjaRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/regulamin': {
      id: '/(public)/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof publicRegulaminRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/logowanie': {
      id: '/(public)/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof publicLogowanieRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/kontakt': {
      id: '/(public)/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof publicKontaktRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/funkcje': {
      id: '/(public)/funkcje'
      path: '/funkcje'
      fullPath: '/funkcje'
      preLoaderRoute: typeof publicFunkcjeRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/cennik': {
      id: '/(public)/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof publicCennikRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/dashboard/issues/': {
      id: '/dashboard/issues/'
      path: '/issues'
      fullPath: '/dashboard/issues/'
      preLoaderRoute: typeof DashboardIssuesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment/': {
      id: '/dashboard/equipment/'
      path: '/equipment'
      fullPath: '/dashboard/equipment/'
      preLoaderRoute: typeof DashboardEquipmentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issues/archive': {
      id: '/dashboard/issues/archive'
      path: '/issues/archive'
      fullPath: '/dashboard/issues/archive'
      preLoaderRoute: typeof DashboardIssuesArchiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issues/$id': {
      id: '/dashboard/issues/$id'
      path: '/issues/$id'
      fullPath: '/dashboard/issues/$id'
      preLoaderRoute: typeof DashboardIssuesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment/add': {
      id: '/dashboard/equipment/add'
      path: '/equipment/add'
      fullPath: '/dashboard/equipment/add'
      preLoaderRoute: typeof DashboardEquipmentAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment/$id': {
      id: '/dashboard/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/dashboard/equipment/$id'
      preLoaderRoute: typeof DashboardEquipmentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicCennikRoute: typeof publicCennikRoute
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicFunkcjeRoute: typeof publicFunkcjeRoute
  publicKontaktRoute: typeof publicKontaktRoute
  publicLogowanieRoute: typeof publicLogowanieRoute
  publicRegulaminRoute: typeof publicRegulaminRoute
  publicRejestracjaRoute: typeof publicRejestracjaRoute
  publicResetPasswordRoute: typeof publicResetPasswordRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicCennikRoute: publicCennikRoute,
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicFunkcjeRoute: publicFunkcjeRoute,
  publicKontaktRoute: publicKontaktRoute,
  publicLogowanieRoute: publicLogowanieRoute,
  publicRegulaminRoute: publicRegulaminRoute,
  publicRejestracjaRoute: publicRejestracjaRoute,
  publicResetPasswordRoute: publicResetPasswordRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface DashboardRouteChildren {
  DashboardFeedbackRoute: typeof DashboardFeedbackRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEquipmentIdRoute: typeof DashboardEquipmentIdRoute
  DashboardEquipmentAddRoute: typeof DashboardEquipmentAddRoute
  DashboardIssuesIdRoute: typeof DashboardIssuesIdRoute
  DashboardIssuesArchiveRoute: typeof DashboardIssuesArchiveRoute
  DashboardEquipmentIndexRoute: typeof DashboardEquipmentIndexRoute
  DashboardIssuesIndexRoute: typeof DashboardIssuesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFeedbackRoute: DashboardFeedbackRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEquipmentIdRoute: DashboardEquipmentIdRoute,
  DashboardEquipmentAddRoute: DashboardEquipmentAddRoute,
  DashboardIssuesIdRoute: DashboardIssuesIdRoute,
  DashboardIssuesArchiveRoute: DashboardIssuesArchiveRoute,
  DashboardEquipmentIndexRoute: DashboardEquipmentIndexRoute,
  DashboardIssuesIndexRoute: DashboardIssuesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
