/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardFeedbackRouteImport } from './routes/dashboard/feedback'
import { Route as publicSignupRouteImport } from './routes/(public)/signup'
import { Route as publicResetPasswordRouteImport } from './routes/(public)/reset-password'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicKontaktRouteImport } from './routes/(public)/kontakt'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as publicCennikRouteImport } from './routes/(public)/cennik'
import { Route as DashboardIssuesIndexRouteImport } from './routes/dashboard/issues.index'
import { Route as DashboardEquipmentIndexRouteImport } from './routes/dashboard/equipment.index'
import { Route as publicMozliwosciIndexRouteImport } from './routes/(public)/mozliwosci/index'
import { Route as publicBranzeIndexRouteImport } from './routes/(public)/branze/index'
import { Route as DashboardIssuesArchiveRouteImport } from './routes/dashboard/issues.archive'
import { Route as DashboardIssuesIdRouteImport } from './routes/dashboard/issues.$id'
import { Route as DashboardEquipmentAddRouteImport } from './routes/dashboard/equipment.add'
import { Route as DashboardEquipmentIdRouteImport } from './routes/dashboard/equipment.$id'
import { Route as publicMozliwosciPowiadomieniaRouteImport } from './routes/(public)/mozliwosci/powiadomienia'
import { Route as publicMozliwosciHistoriaNaprawRouteImport } from './routes/(public)/mozliwosci/historia-napraw'
import { Route as publicMozliwosciGeneratorKodowQrRouteImport } from './routes/(public)/mozliwosci/generator-kodow-qr'
import { Route as publicMozliwosciFormularzZgloszeniowyRouteImport } from './routes/(public)/mozliwosci/formularz-zgloszeniowy'
import { Route as publicBranzeSilownieRouteImport } from './routes/(public)/branze/silownie'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeedbackRoute = DashboardFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DashboardRoute,
} as any)
const publicSignupRoute = publicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicResetPasswordRoute = publicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicKontaktRoute = publicKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCennikRoute = publicCennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => publicRouteRoute,
} as any)
const DashboardIssuesIndexRoute = DashboardIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentIndexRoute = DashboardEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => DashboardRoute,
} as any)
const publicMozliwosciIndexRoute = publicMozliwosciIndexRouteImport.update({
  id: '/mozliwosci/',
  path: '/mozliwosci/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicBranzeIndexRoute = publicBranzeIndexRouteImport.update({
  id: '/branze/',
  path: '/branze/',
  getParentRoute: () => publicRouteRoute,
} as any)
const DashboardIssuesArchiveRoute = DashboardIssuesArchiveRouteImport.update({
  id: '/issues/archive',
  path: '/issues/archive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssuesIdRoute = DashboardIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentAddRoute = DashboardEquipmentAddRouteImport.update({
  id: '/equipment/add',
  path: '/equipment/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentIdRoute = DashboardEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const publicMozliwosciPowiadomieniaRoute =
  publicMozliwosciPowiadomieniaRouteImport.update({
    id: '/mozliwosci/powiadomienia',
    path: '/mozliwosci/powiadomienia',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicMozliwosciHistoriaNaprawRoute =
  publicMozliwosciHistoriaNaprawRouteImport.update({
    id: '/mozliwosci/historia-napraw',
    path: '/mozliwosci/historia-napraw',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicMozliwosciGeneratorKodowQrRoute =
  publicMozliwosciGeneratorKodowQrRouteImport.update({
    id: '/mozliwosci/generator-kodow-qr',
    path: '/mozliwosci/generator-kodow-qr',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicMozliwosciFormularzZgloszeniowyRoute =
  publicMozliwosciFormularzZgloszeniowyRouteImport.update({
    id: '/mozliwosci/formularz-zgloszeniowy',
    path: '/mozliwosci/formularz-zgloszeniowy',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicBranzeSilownieRoute = publicBranzeSilownieRouteImport.update({
  id: '/branze/silownie',
  path: '/branze/silownie',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/cennik': typeof publicCennikRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/kontakt': typeof publicKontaktRoute
  '/login': typeof publicLoginRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/signup': typeof publicSignupRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/branze/silownie': typeof publicBranzeSilownieRoute
  '/mozliwosci/formularz-zgloszeniowy': typeof publicMozliwosciFormularzZgloszeniowyRoute
  '/mozliwosci/generator-kodow-qr': typeof publicMozliwosciGeneratorKodowQrRoute
  '/mozliwosci/historia-napraw': typeof publicMozliwosciHistoriaNaprawRoute
  '/mozliwosci/powiadomienia': typeof publicMozliwosciPowiadomieniaRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/equipment/add': typeof DashboardEquipmentAddRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/branze/': typeof publicBranzeIndexRoute
  '/mozliwosci/': typeof publicMozliwosciIndexRoute
  '/dashboard/equipment/': typeof DashboardEquipmentIndexRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/cennik': typeof publicCennikRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/kontakt': typeof publicKontaktRoute
  '/login': typeof publicLoginRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/signup': typeof publicSignupRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/branze/silownie': typeof publicBranzeSilownieRoute
  '/mozliwosci/formularz-zgloszeniowy': typeof publicMozliwosciFormularzZgloszeniowyRoute
  '/mozliwosci/generator-kodow-qr': typeof publicMozliwosciGeneratorKodowQrRoute
  '/mozliwosci/historia-napraw': typeof publicMozliwosciHistoriaNaprawRoute
  '/mozliwosci/powiadomienia': typeof publicMozliwosciPowiadomieniaRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/equipment/add': typeof DashboardEquipmentAddRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/branze': typeof publicBranzeIndexRoute
  '/mozliwosci': typeof publicMozliwosciIndexRoute
  '/dashboard/equipment': typeof DashboardEquipmentIndexRoute
  '/dashboard/issues': typeof DashboardIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/(public)/cennik': typeof publicCennikRoute
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/kontakt': typeof publicKontaktRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/reset-password': typeof publicResetPasswordRoute
  '/(public)/signup': typeof publicSignupRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/(public)/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(public)/branze/silownie': typeof publicBranzeSilownieRoute
  '/(public)/mozliwosci/formularz-zgloszeniowy': typeof publicMozliwosciFormularzZgloszeniowyRoute
  '/(public)/mozliwosci/generator-kodow-qr': typeof publicMozliwosciGeneratorKodowQrRoute
  '/(public)/mozliwosci/historia-napraw': typeof publicMozliwosciHistoriaNaprawRoute
  '/(public)/mozliwosci/powiadomienia': typeof publicMozliwosciPowiadomieniaRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/equipment/add': typeof DashboardEquipmentAddRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/(public)/branze/': typeof publicBranzeIndexRoute
  '/(public)/mozliwosci/': typeof publicMozliwosciIndexRoute
  '/dashboard/equipment/': typeof DashboardEquipmentIndexRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/cennik'
    | '/forgot-password'
    | '/kontakt'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/feedback'
    | '/dashboard/settings'
    | '/'
    | '/dashboard/'
    | '/branze/silownie'
    | '/mozliwosci/formularz-zgloszeniowy'
    | '/mozliwosci/generator-kodow-qr'
    | '/mozliwosci/historia-napraw'
    | '/mozliwosci/powiadomienia'
    | '/dashboard/equipment/$id'
    | '/dashboard/equipment/add'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/branze/'
    | '/mozliwosci/'
    | '/dashboard/equipment/'
    | '/dashboard/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cennik'
    | '/forgot-password'
    | '/kontakt'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/feedback'
    | '/dashboard/settings'
    | '/'
    | '/dashboard'
    | '/branze/silownie'
    | '/mozliwosci/formularz-zgloszeniowy'
    | '/mozliwosci/generator-kodow-qr'
    | '/mozliwosci/historia-napraw'
    | '/mozliwosci/powiadomienia'
    | '/dashboard/equipment/$id'
    | '/dashboard/equipment/add'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/branze'
    | '/mozliwosci'
    | '/dashboard/equipment'
    | '/dashboard/issues'
  id:
    | '__root__'
    | '/(public)'
    | '/dashboard'
    | '/(public)/cennik'
    | '/(public)/forgot-password'
    | '/(public)/kontakt'
    | '/(public)/login'
    | '/(public)/reset-password'
    | '/(public)/signup'
    | '/dashboard/feedback'
    | '/dashboard/settings'
    | '/(public)/'
    | '/dashboard/'
    | '/(public)/branze/silownie'
    | '/(public)/mozliwosci/formularz-zgloszeniowy'
    | '/(public)/mozliwosci/generator-kodow-qr'
    | '/(public)/mozliwosci/historia-napraw'
    | '/(public)/mozliwosci/powiadomienia'
    | '/dashboard/equipment/$id'
    | '/dashboard/equipment/add'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/(public)/branze/'
    | '/(public)/mozliwosci/'
    | '/dashboard/equipment/'
    | '/dashboard/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feedback': {
      id: '/dashboard/feedback'
      path: '/feedback'
      fullPath: '/dashboard/feedback'
      preLoaderRoute: typeof DashboardFeedbackRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/reset-password': {
      id: '/(public)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof publicResetPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/kontakt': {
      id: '/(public)/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof publicKontaktRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/cennik': {
      id: '/(public)/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof publicCennikRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/dashboard/issues/': {
      id: '/dashboard/issues/'
      path: '/issues'
      fullPath: '/dashboard/issues/'
      preLoaderRoute: typeof DashboardIssuesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment/': {
      id: '/dashboard/equipment/'
      path: '/equipment'
      fullPath: '/dashboard/equipment/'
      preLoaderRoute: typeof DashboardEquipmentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(public)/mozliwosci/': {
      id: '/(public)/mozliwosci/'
      path: '/mozliwosci'
      fullPath: '/mozliwosci/'
      preLoaderRoute: typeof publicMozliwosciIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/branze/': {
      id: '/(public)/branze/'
      path: '/branze'
      fullPath: '/branze/'
      preLoaderRoute: typeof publicBranzeIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/dashboard/issues/archive': {
      id: '/dashboard/issues/archive'
      path: '/issues/archive'
      fullPath: '/dashboard/issues/archive'
      preLoaderRoute: typeof DashboardIssuesArchiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issues/$id': {
      id: '/dashboard/issues/$id'
      path: '/issues/$id'
      fullPath: '/dashboard/issues/$id'
      preLoaderRoute: typeof DashboardIssuesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment/add': {
      id: '/dashboard/equipment/add'
      path: '/equipment/add'
      fullPath: '/dashboard/equipment/add'
      preLoaderRoute: typeof DashboardEquipmentAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment/$id': {
      id: '/dashboard/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/dashboard/equipment/$id'
      preLoaderRoute: typeof DashboardEquipmentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(public)/mozliwosci/powiadomienia': {
      id: '/(public)/mozliwosci/powiadomienia'
      path: '/mozliwosci/powiadomienia'
      fullPath: '/mozliwosci/powiadomienia'
      preLoaderRoute: typeof publicMozliwosciPowiadomieniaRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/mozliwosci/historia-napraw': {
      id: '/(public)/mozliwosci/historia-napraw'
      path: '/mozliwosci/historia-napraw'
      fullPath: '/mozliwosci/historia-napraw'
      preLoaderRoute: typeof publicMozliwosciHistoriaNaprawRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/mozliwosci/generator-kodow-qr': {
      id: '/(public)/mozliwosci/generator-kodow-qr'
      path: '/mozliwosci/generator-kodow-qr'
      fullPath: '/mozliwosci/generator-kodow-qr'
      preLoaderRoute: typeof publicMozliwosciGeneratorKodowQrRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/mozliwosci/formularz-zgloszeniowy': {
      id: '/(public)/mozliwosci/formularz-zgloszeniowy'
      path: '/mozliwosci/formularz-zgloszeniowy'
      fullPath: '/mozliwosci/formularz-zgloszeniowy'
      preLoaderRoute: typeof publicMozliwosciFormularzZgloszeniowyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/branze/silownie': {
      id: '/(public)/branze/silownie'
      path: '/branze/silownie'
      fullPath: '/branze/silownie'
      preLoaderRoute: typeof publicBranzeSilownieRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicCennikRoute: typeof publicCennikRoute
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicKontaktRoute: typeof publicKontaktRoute
  publicLoginRoute: typeof publicLoginRoute
  publicResetPasswordRoute: typeof publicResetPasswordRoute
  publicSignupRoute: typeof publicSignupRoute
  publicIndexRoute: typeof publicIndexRoute
  publicBranzeSilownieRoute: typeof publicBranzeSilownieRoute
  publicMozliwosciFormularzZgloszeniowyRoute: typeof publicMozliwosciFormularzZgloszeniowyRoute
  publicMozliwosciGeneratorKodowQrRoute: typeof publicMozliwosciGeneratorKodowQrRoute
  publicMozliwosciHistoriaNaprawRoute: typeof publicMozliwosciHistoriaNaprawRoute
  publicMozliwosciPowiadomieniaRoute: typeof publicMozliwosciPowiadomieniaRoute
  publicBranzeIndexRoute: typeof publicBranzeIndexRoute
  publicMozliwosciIndexRoute: typeof publicMozliwosciIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicCennikRoute: publicCennikRoute,
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicKontaktRoute: publicKontaktRoute,
  publicLoginRoute: publicLoginRoute,
  publicResetPasswordRoute: publicResetPasswordRoute,
  publicSignupRoute: publicSignupRoute,
  publicIndexRoute: publicIndexRoute,
  publicBranzeSilownieRoute: publicBranzeSilownieRoute,
  publicMozliwosciFormularzZgloszeniowyRoute:
    publicMozliwosciFormularzZgloszeniowyRoute,
  publicMozliwosciGeneratorKodowQrRoute: publicMozliwosciGeneratorKodowQrRoute,
  publicMozliwosciHistoriaNaprawRoute: publicMozliwosciHistoriaNaprawRoute,
  publicMozliwosciPowiadomieniaRoute: publicMozliwosciPowiadomieniaRoute,
  publicBranzeIndexRoute: publicBranzeIndexRoute,
  publicMozliwosciIndexRoute: publicMozliwosciIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface DashboardRouteChildren {
  DashboardFeedbackRoute: typeof DashboardFeedbackRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEquipmentIdRoute: typeof DashboardEquipmentIdRoute
  DashboardEquipmentAddRoute: typeof DashboardEquipmentAddRoute
  DashboardIssuesIdRoute: typeof DashboardIssuesIdRoute
  DashboardIssuesArchiveRoute: typeof DashboardIssuesArchiveRoute
  DashboardEquipmentIndexRoute: typeof DashboardEquipmentIndexRoute
  DashboardIssuesIndexRoute: typeof DashboardIssuesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFeedbackRoute: DashboardFeedbackRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEquipmentIdRoute: DashboardEquipmentIdRoute,
  DashboardEquipmentAddRoute: DashboardEquipmentAddRoute,
  DashboardIssuesIdRoute: DashboardIssuesIdRoute,
  DashboardIssuesArchiveRoute: DashboardIssuesArchiveRoute,
  DashboardEquipmentIndexRoute: DashboardEquipmentIndexRoute,
  DashboardIssuesIndexRoute: DashboardIssuesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
