/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BranzeIndexRouteImport } from './routes/branze/index'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DashboardEquipmentRouteImport } from './routes/dashboard.equipment'
import { Route as BranzeSilownieRouteImport } from './routes/branze/silownie'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as DashboardIssuesIndexRouteImport } from './routes/dashboard.issues.index'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DashboardIssuesArchiveRouteImport } from './routes/dashboard.issues.archive'
import { Route as DashboardIssuesIdRouteImport } from './routes/dashboard.issues.$id'

const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BranzeIndexRoute = BranzeIndexRouteImport.update({
  id: '/branze/',
  path: '/branze/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEquipmentRoute = DashboardEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => DashboardRoute,
} as any)
const BranzeSilownieRoute = BranzeSilownieRouteImport.update({
  id: '/branze/silownie',
  path: '/branze/silownie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssuesIndexRoute = DashboardIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIssuesArchiveRoute = DashboardIssuesArchiveRouteImport.update({
  id: '/issues/archive',
  path: '/issues/archive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssuesIdRoute = DashboardIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/branze/silownie': typeof BranzeSilownieRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/demo/convex': typeof DemoConvexRoute
  '/branze/': typeof BranzeIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/branze/silownie': typeof BranzeSilownieRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/demo/convex': typeof DemoConvexRoute
  '/branze': typeof BranzeIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/dashboard/issues': typeof DashboardIssuesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/branze/silownie': typeof BranzeSilownieRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/demo/convex': typeof DemoConvexRoute
  '/branze/': typeof BranzeIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/issues/$id': typeof DashboardIssuesIdRoute
  '/dashboard/issues/archive': typeof DashboardIssuesArchiveRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cennik'
    | '/dashboard'
    | '/faq'
    | '/kontakt'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/branze/silownie'
    | '/dashboard/equipment'
    | '/demo/convex'
    | '/branze/'
    | '/dashboard/'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/dashboard/issues/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik'
    | '/faq'
    | '/kontakt'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/branze/silownie'
    | '/dashboard/equipment'
    | '/demo/convex'
    | '/branze'
    | '/dashboard'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/dashboard/issues'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/cennik'
    | '/dashboard'
    | '/faq'
    | '/kontakt'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/branze/silownie'
    | '/dashboard/equipment'
    | '/demo/convex'
    | '/branze/'
    | '/dashboard/'
    | '/dashboard/issues/$id'
    | '/dashboard/issues/archive'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/dashboard/issues/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CennikRoute: typeof CennikRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BranzeSilownieRoute: typeof BranzeSilownieRoute
  DemoConvexRoute: typeof DemoConvexRoute
  BranzeIndexRoute: typeof BranzeIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/branze/': {
      id: '/branze/'
      path: '/branze'
      fullPath: '/branze/'
      preLoaderRoute: typeof BranzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/equipment': {
      id: '/dashboard/equipment'
      path: '/equipment'
      fullPath: '/dashboard/equipment'
      preLoaderRoute: typeof DashboardEquipmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/branze/silownie': {
      id: '/branze/silownie'
      path: '/branze/silownie'
      fullPath: '/branze/silownie'
      preLoaderRoute: typeof BranzeSilownieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issues/': {
      id: '/dashboard/issues/'
      path: '/issues'
      fullPath: '/dashboard/issues/'
      preLoaderRoute: typeof DashboardIssuesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/issues/archive': {
      id: '/dashboard/issues/archive'
      path: '/issues/archive'
      fullPath: '/dashboard/issues/archive'
      preLoaderRoute: typeof DashboardIssuesArchiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issues/$id': {
      id: '/dashboard/issues/$id'
      path: '/issues/$id'
      fullPath: '/dashboard/issues/$id'
      preLoaderRoute: typeof DashboardIssuesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEquipmentRoute: typeof DashboardEquipmentRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardIssuesIdRoute: typeof DashboardIssuesIdRoute
  DashboardIssuesArchiveRoute: typeof DashboardIssuesArchiveRoute
  DashboardIssuesIndexRoute: typeof DashboardIssuesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEquipmentRoute: DashboardEquipmentRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardIssuesIdRoute: DashboardIssuesIdRoute,
  DashboardIssuesArchiveRoute: DashboardIssuesArchiveRoute,
  DashboardIssuesIndexRoute: DashboardIssuesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CennikRoute: CennikRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  BranzeSilownieRoute: BranzeSilownieRoute,
  DemoConvexRoute: DemoConvexRoute,
  BranzeIndexRoute: BranzeIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
